version: 2.1

orbs:
  ci: geos-esm/circleci-tools@1

workflows:
  build-test:
    jobs:
      - ci/build:
          name: build-RadApp-on-<< matrix.compiler >>
          context:
            - docker-hub-creds
          matrix:
            parameters:
              compiler:
                - gfortran
                - ifort
          repo: RadApp
          mepodevelop: false # Until RadApp is up-to-date with GEOSgcm, turn off mepodevelop
          develop_repos: GEOSgcm_GridComp GMAO_Shared
