version: 2.1

# Anchors to prevent forgetting to update a version
os_version: &os_version ubuntu20
baselibs_version: &baselibs_version v7.7.0
bcs_version: &bcs_version v10.23.0

orbs:
  ci: geos-esm/circleci-tools@1

workflows:
  build-test:
    jobs:
      - ci/build:
          name: build-RadApp-on-<< matrix.compiler >>
          context:
            - docker-hub-creds
          matrix:
            parameters:
              compiler: [ifort, gfortran]
          baselibs_version: *baselibs_version
          repo: RadApp
          mepodevelop: false # Until RadApp is up-to-date with GEOSgcm, turn off mepodevelop
          develop_repos: GEOSgcm_GridComp GMAO_Shared
